ktor:
  application:
    modules:
      - com.crypto.ApplicationKt.module
  deployment:
    port: 7102
  watch:
    - classes
    - resources
crypto:
  repository:
    test: "cassandra"
    prod: "cassandra"
    cassandra:
      hosts: localhost
      port: 9042
      keyspace: test_keyspace
      username: cassandra
      password: cassandra

jwt:
  issuer: "http://localhost:8081/auth/realms/crypto-exchange"
  audience: "order-user"
  realm: "crypto-exchange-realm"
  clientId: "crypto-exchange-order"
  certUrl: "http://localhost:8081/auth/realms/crypto-exchange/protocol/openid-connect/certs" # TODO()