# This is a basic workflow to help you get started with Actions

name: 'CI-build'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - 'main'
      - 'master'
      - 'develop'
      - 'v-*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'main'
      - 'master'
      - 'develop'
      - 'v-*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-22.04
#    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Run Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check

#      - name: List Tests
#        run: ls .;echo "---build";ls build/;echo "---test-results"; ls build/test-results/;echo "---jvmTest"; ls build/test-results/jvmTest/
#
#      - name: Test Report
#        uses: dorny/test-reporter@v1
#        if: success() || failure()
#        with:
#          name: Unit Test Results
#          path: build/test-results/**/*.xml
#          reporter: java-junit

      - name: Run detekt
        run: ./gradlew detekt

      # Make sure we always run this upload task,
      # because the previous step may fail if there are findings.
      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/detekt.sarif