# This is a basic workflow to help you get started with Actions

name: 'CI-test'

# Controls when the workflow will run
on:
  push:
    branches-ignore:
      - 'v-*'
      - 'main'
      - 'master'
      - 'develop'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-22.04
#    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Test package
        run: gradle check

#      - name: Report unit tests
#        uses: dorny/test-reporter@v1
#        if: always()
#        with:
#          name: Gradle Tests
#          path: '**/build/test-results/*/TEST-*.xml'
#          reporter: java-junit
#          fail-on-error: true

      - name: Run detekt
        run: ./gradlew detekt

      # Make sure we always run this upload task,
      # because the previous step may fail if there are findings.
      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/detekt.sarif